### ISSUE TITLE
Error in analyzing soilmoisture

### ISSUE THREAD

**Issue by dhakalsandesh33** [sepal-contrib/sepal_pysmm#37]
Dear bridge, 
I have tried analyzing the soil moisture of my interest area from SEPAL. But, while performing statistical analysis and selecting the date selection, the error have been appeared "CardText' object is not subscriptable". what does it mean? how can i resolve this issue?

**Comment by dfguerrerom** [comment]
that error was preventing to display the images that were going to be used in the stack composition process, however you could perform the statistical analysis.

The error was fixed by updating sepal version https://github.com/sepal-contrib/sepal_pysmm/commit/8769ad99650915bd6d2b2e09898086530447ec63.
