### ISSUE TITLE
Error in Map visualization under Sepal Soil Moisture Mapping

### ISSUE THREAD

**Issue by dhakalsandesh33** [sepal-contrib/sepal_pysmm#38]
Dear bridge,
I have tried map visualization for soil moisture assessment of my interest area from SEPAL. But, while performing display image and selecting the date, the error have been appeared "Your environment is not compatible with local tile server, please check https://localtileserver.banesullivan.com/installation/index.html for more information". what does it mean? how can i resolve this issue?

**Comment by 12rambau** [comment]
I'm not the maintainer of this application but this issue is related to an upstream problem between SEPAL and Python application. We are working toward a solution, there is unfortunately nothing you can do at the moment.
Note that this error is normally just preventing the display of locally computed images on the interactive map. The tiff file should be created anyway.

**Comment by dfguerrerom** [comment]
this is related with https://github.com/sepal-contrib/sepal_pysmm/issues/33
